---
- name: Remove httpd packages
  hosts: webservers
  become: true
  tasks: 
  - name: Stop service
    service: 
      name: httpd
      state: stopped

  - name: Remove hhtpd packages
    yum: 
      name: httpd
      state: removed
