---
- name: Uninstall packages httpd on RedHat OS family
  hosts: all
  become: true
  tasks:
  - name: stop httpd on Redhat Family
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Uninstall httpd on RedHat Family
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"


  - name: Stop apache2 on Debian Family
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: Uninstall apache2 on Debian Family
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"


