---
# tasks file for setup-apache


  - name: Install httpd on Redhat family
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "Redhat"
    notify: start httpd


  - name: Install apache2 on Debian family
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2




  - name: copy index.html to managed nodes
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666


  - name: Ensure that default apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen'
      insertafter: '^#Listen'
      line: Listen 8081
    when: ansible_os_family == "RedHat"
    notify: restart apache



  - name: Ensure that default apache2 port is {{ port }}
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen'
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen 8081
    when: ansible_os_family == "Debian"
    notify: restart apache2
